import 'normalize.css'
import 'src/style/variable.css'
import 'src/style/reset.css'
import 'src/style/global.css'
import 'src/style/fonts.css'
import { Inter } from 'next/font/google'
import styles from 'src/app/layout.module.scss'
import Navigation from 'src/components/nav'
import { getNavigation } from 'src/data-fetching/home'
import StyledJsxRegistry from 'src/lib/registry'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'oh-my-note',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const nav = await getNavigation()
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles['page-header']}>
          <div className={styles['logo']}>oh-my-note</div>

          <Navigation nav={nav} />
        </header>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  )
}
